### ISSUE TITLE
lowercase openid causes status 500 error

### ISSUE THREAD

**Issue by ty-** [adlnet/ADL_LRS#317]
[Issue #330](https://github.com/adlnet/xAPI-Spec/issues/330) in the spec discusses a typo ```openID``` which is now uniformly lowercase.

> Status 500 INTERNAL SERVER ERROR: Cannot resolve keyword 'openid' into field. Choices are: account_homePage, account_name, activity, activitystate, actor_of_substatement, actor_statement, agentprofile, authority_statement, canonical_version, id, mbox, mbox_sha1sum, member, name, oauth_identifier, objectType, object_of_statement, object_of_substatement, openID, statement_context_instructor, statement_context_team, substatement_context_instructor, substatement_context_team

The LRS should accept ```openid```. I'm unclear as to whether @garemoko means ```openID``` should be translated to ```openid``` before adding the statement to the database in his last comment on the issue.

**Comment by garemoko** [comment]
That does appear to have been my intention at the time, however that never made it into the PR. In fact, the spec now says:

```The LRS MUST reject with HTTP 400 Bad Request status any request to any of these APIs that use any parameters matching parameters described in this specification in all but case. ```

I believe this was added partly in response to the openid issue, but even if not, it's pretty clear.
