### ISSUE TITLE
Should an anonymous Group object with an empty member array be accepted?

### ISSUE THREAD

**Issue by ty-** [adlnet/ADL_LRS#318]
I was able to send the following statement to the LRS successfully:

```javascript
{
    "verb": {
        "id": "http://adlnet.gov/expapi/verbs/attended",
        "display": {
            "en-US": "attended"
        }
    },
    "version": "1.0.0",
    "timestamp": "2015-02-15T23:28:09.960399+00:00",
    "object": {
        "member": [],
        "name": "",
        "objectType": "Group"
    },
    "actor": {
        "mbox": "mailto:tyler.mulligan.ctr@adlnet.gov",
        "name": "Tyler",
        "objectType": "Agent"
    },
    "stored": "2015-02-15T23:28:09.960399+00:00",
    "authority": {
        "mbox": "mailto:tyler.mulligan.ctr+xapi-tools@adlnet.gov",
        "name": "xapi-tools",
        "objectType": "Agent"
    },
    "id": "8db7efc4-3f3b-4119-b677-cc0ea4175ad1"
}
```

The spec states:
> An Anonymous Group MUST include a 'member' property listing constituent Agents.

It's unclear whether the listing can be empty.

**Comment by garemoko** [comment]
I think ```listing constituent Agents``` is pretty clear that some agents are supposed to be listed. 

Also:

``` An Activity Provider MAY include a complete or partial list of Agents in the 'member' property of a given Anonymous or Identified Group. ```

No list is not a partial list.
