### ISSUE TITLE
Getting 200 against statements endpoint w/ wrong Authorization

### ISSUE THREAD

**Issue by varunasingh** [adlnet/ADL_LRS#341]
Hi, 

Can someone try to send the following requst to the LRS endpoint/statements?limit=1
Add the X-Experience header like: 
name: X-Experience-API-Version 
value: 1.0.1
Also add an "Authorization" header:
name: Authorization
value: blah blah blah

I get a 200 OK . If the same is happening at your end, then can anyone explain why. 
If not, then It must be something on my end that I'm doing wrong. 

thanks

**Comment by creighton** [comment]
I'm getting the same thing. I'll look into it.
