### ISSUE TITLE
About the speed of posting statements in LRS

### ISSUE THREAD

**Issue by SrarHu** [adlnet/ADL_LRS#378]
I have set up LRS in virtual machine, but I found the POST or PUT speed is about 6~8 statements per second, it's so low that cannot meet my demand.
Do there have somethings wrong with the speed?

**Comment by garemoko** [comment]
@SrarHu the position may have changed but when this LRS was first created the idea was for it to be a reference implementation rather than something for use in production. I don't know how other open source LRSs stand in terms of statements per second, but you should certainly expect to get much higher figures from a commercial LRS.

**Comment by ljwolford** [comment]
@SrarHu is this happening with every single request? We haven't been experiencing these slow speeds with the hosted LRS or our local test instances. In the past we've learned that if celery isn't working properly it will cause a long delay in the POSTing or PUTing of statements. Maybe not enough memory is allocated in your virtual machine?

**Comment by SrarHu** [comment]
@ljwolford the speed is average when I posting about 10000 statements. I will check celery and try to add memory of my virtual machine.
Can I ask you what's the speed of your official LRS？

**Comment by ljwolford** [comment]
For POSTing a batch of 10000 statements at once,  a local instance of ours averages 9 milliseconds per statement. My test virtual machine only has about 2GB of memory. As Andrew said this is just a reference implementation and if you have anything critical relying on an LRS I suggest looking into commercial options. Keep me updated if you find anything wrong with the celery setup. Thank you.

**Comment by fugu13** [comment]
@SrarHu are you posting/putting those statements one after another, waiting for the previous to complete, from a single application? If that's the case, my guess would be this is more a round trip latency issue, and can be solved by parallel or batch submission.

**Comment by ljwolford** [comment]
closed due to inactivity
