### ISSUE TITLE
500 [Errno 111] Connection refused

### ISSUE THREAD

**Issue by evermax** [adlnet/ADL_LRS#379]
Hi!

I've been trying to make the project run in a Docker container.
After some tuning, which you can see [here on my fork](https://github.com/adlnet/ADL_LRS/compare/master...evermax:master) (note that I also put I18N=False in the settings.py so it doesn't try to use the translation part your fix was for), I've been able to make the project run, apparently correctly, I was able to go in the admin, add/remove users, etc. But when I post a statement, I got a 500 with for only content: [Errno 111] Connection refused.

So I looked into you issues, you were saying that it should be run with uwsgi and nginx and that might be the reason why. So I did it and ended up with the same issue.

Here is the stack for this error.
```
2016-01-29 04:47:38,813 [INFO] lrs.views:
Exception while processing: /xAPI/statements
2016-01-29 04:47:38,814 [ERROR] lrs.views: [Errno 111] Connection refused
Traceback (most recent call last):
  File "./lrs/views.py", line 209, in handle_request
    return processors[path][req_dict['method']](req_dict)
  File "./lrs/utils/req_process.py", line 127, in statements_post
    check_activity_metadata.delay(stmt_ids)
  File "/workspace/env/lib/python2.7/site-packages/celery/app/task.py", line 453, in delay
    return self.apply_async(args, kwargs)
  File "/workspace/env/lib/python2.7/site-packages/celery/app/task.py", line 559, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/workspace/env/lib/python2.7/site-packages/celery/app/base.py", line 353, in send_task
    reply_to=reply_to or self.oid, **options
  File "/workspace/env/lib/python2.7/site-packages/celery/app/amqp.py", line 305, in publish_task
    **kwargs
  File "/workspace/env/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/workspace/env/lib/python2.7/site-packages/kombu/connection.py", line 457, in _ensured
    interval_max)
  File "/workspace/env/lib/python2.7/site-packages/kombu/connection.py", line 369, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/workspace/env/lib/python2.7/site-packages/kombu/utils/__init__.py", line 246, in retry_over_time
    return fun(*args, **kwargs)
  File "/workspace/env/lib/python2.7/site-packages/kombu/connection.py", line 237, in connect
    return self.connection
  File "/workspace/env/lib/python2.7/site-packages/kombu/connection.py", line 741, in connection
    self._connection = self._establish_connection()
  File "/workspace/env/lib/python2.7/site-packages/kombu/connection.py", line 696, in _establish_connection
    conn = self.transport.establish_connection()
  File "/workspace/env/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
    conn = self.Connection(**opts)
  File "/workspace/env/lib/python2.7/site-packages/amqp/connection.py", line 165, in __init__
    self.transport = self.Transport(host, connect_timeout, ssl)
  File "/workspace/env/lib/python2.7/site-packages/amqp/connection.py", line 186, in Transport
    return create_transport(host, connect_timeout, ssl)
  File "/workspace/env/lib/python2.7/site-packages/amqp/transport.py", line 299, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/workspace/env/lib/python2.7/site-packages/amqp/transport.py", line 95, in __init__
    raise socket.error(last_err)
error: [Errno 111] Connection refused
```

Do you have any tip?
I tried to spin up a droplet on Digital Ocean and had the same issue with just `python ./manage.py run server`. I could try spin up a new one, install everything required again and see if I get the 500 again, but you might have an idea about what is going on.

**Comment by ljwolford** [comment]
Hello,

That looks like it's from the lrs.log...can you check what is listed in your celery or supervisor log files? The function, check_activity_metadata, is being used by celery so I have a feeling something screwy is going on with it or supervisor. It could also be a rabbitmq issue. Make sure you're using the correct username and password inside of the broker parameter in the celery.py file listed in the lrs/ app.

**Comment by evermax** [comment]
Thanks @ljwolford for the answer. I am trying to use the project out of the box to be honest. I am not really familiar with developing in Django so I am going to ask some pretty stupid questions: do I need supervisor for this project? I am using nginx and uwgsi. And I definitely missed something: I need rabbitmq for this project to run? :interrobang:

**Comment by evermax** [comment]
Ok, thank you very much @ljwolford for this, it wad the RabbitMQ config that was missing!
I am curious though, why is RabbitMQ necessary for the project?
I didn't see any mention about it in either the readme or the Wiki, at least not in the pages I was looking at.

**Comment by ljwolford** [comment]
No problem...so in a nutshell, the LRS runs on Django. Django provides a test web server that gets ran when you run the command 'python manage.py runserver'. This is perfect for when you just need to run it locally to test with it. If you want to try to set it up for a few people to use, we use uwsgi as the application container/server. Since uwsgi doesn't serve static content, hook it up to nginx so nginx just has to worry about it (and this stack is widely used). So while you're testing or just keeping the LRS local, you don't need uwsgi or nginx, but anything outside of that you should have a separate web server running the LRS (and in our case we chose the uwsgi + nginx combo).

We use celery for tasks that can happen after the user gets a response from the LRS so responses get sent faster. Celery is just a task queue that runs asynchronously from the main process and it requires a message brokering system to pass it's tasks back and forth. In our case rabbitmq is the message brokering system. So rabbitmq runs in the background listening for celery tasks. Supervisor is used to monitor and control the celery processes so they can just hide in the background and so they're easier to stop/start.

Here's the wiki page that has the celery installation laid out, including rabbitmq: https://github.com/adlnet/ADL_LRS/wiki/Using-Celery

I hope that clears some things up!

**Comment by evermax** [comment]
Thank you, it is much clearer indeed!
I'll keep toying with it and when I have a clear Docker image, I'll let you know in case you want to have a look at it.

Thanks again for solving my problem so quickly!

**Comment by ljwolford** [comment]
No problem, sounds good.

**Comment by DaTebe** [comment]
@evermax 
I try to use your docker image. It seems to build without errors. When I load the webpage it tells me: "FATAL:  role "root" does not exist". Did you face this error before?

Thanks in advance, Daniel

**Comment by evermax** [comment]
@DaTebe happy to hear it is solved!
If you have any other trouble, just let me know!

----- Mail original -----
De: "DaTebe" <notifications@github.com>
À: "adlnet/ADL_LRS" <ADL_LRS@noreply.github.com>
Cc: "Maxime Lasserre" <maxlasserre@free.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Vendredi 3 Juin 2016 01:52:43
Objet: Re: [adlnet/ADL_LRS] 500 [Errno 111] Connection refused (#379)



@evermax 
I try to use your docker image. It seems to build without errors. When I load the webpage it tells me: "FATAL: role "root" does not exist". Did you face this error before? 

Thanks in advance, Daniel

**Comment by DaTebe** [comment]
@evermax
The Docker Image is very nice. Do you think one can use the latest adl lrs? I am missing webhooks in your version.

**Comment by ljwolford** [comment]
I've been working on including all of the webhook code, it seems like with the last big upgrade we had, some of the webhooks code was lost. I just got it working again locally so a pull request will be available by the end of the day.

**Comment by evermax** [comment]
I'll work on it over the weekend if the pull request is merged then!

@DaTebe do you use the image from docker hub (https://hub.docker.com/r/dirichlet/lrs/) or do you build it yourself?
I might make a better README to make it easier to just grab the image from the hub.

----- Mail original -----
De: "Lou Wolford" <notifications@github.com>
À: "adlnet/ADL_LRS" <ADL_LRS@noreply.github.com>
Cc: "Maxime Lasserre" <maxlasserre@free.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Vendredi 3 Juin 2016 08:51:47
Objet: Re: [adlnet/ADL_LRS] 500 [Errno 111] Connection refused (#379)



I've been working on including all of the webhook code, it seems like with the last big upgrade we had, some of the webhooks code was lost. I just got it working again locally so a pull request will be available by the end of the day.

**Comment by DaTebe** [comment]
Hi 
I'm using the dirichlet/lrs
