### ISSUE TITLE
How to use oauth1 write statements to ADL_LRS

### ISSUE THREAD

**Issue by h568880275** [adlnet/ADL_LRS#382]
I know how to use oauth1 read statements from ADL_LRS by 'oob_example.py'.But how to write statements to ADL_LRS? Who has some example just like 'oob_example.py' to write statements to ADL_LRS?
Thanks a lot.

**Comment by ljwolford** [comment]
Hello,

Once the OAuth handshake process is complete you are free to write/get any data you wish as long as you have the correct OAuth headers being used. In the `access_resource` function we perform a get with the requests library but you can just as easily change that to a put or post to write data. An example would be:

`response = requests.post(oauth_request.get_normalized_http_url(), data={your statements here}, headers=headers, verify=False)`

**Comment by h568880275** [comment]
@ljwolford I solve the problem by your help.Thanks a lot!
