### ISSUE TITLE
ADL LRS installation integration with Moodle @Getsmarter in Cape Town

### ISSUE THREAD

**Issue by kavniekerk01** [adlnet/ADL_LRS#383]
I am currently attempting to install the ADL LRS on a virtual machine. Currently the system is installed, but I am getting errors with testing and setup. I was wanting to know whether the errors logged on the internet have been resolved.

I would be delighted to log these if you can point me to a forum for this sort of problem.

Your assistance would be greatly appreciated.

**Comment by ljwolford** [comment]
HI @kavniekerk01 ,

You can post your logs in this thread and we'll help you out as much as possible.

Thanks!

**Comment by ljwolford** [comment]
closed to inactivity
