### ISSUE TITLE
How to improve the performance of ADL_LRS?

### ISSUE THREAD

**Issue by HeyLynne** [adlnet/ADL_LRS#392]
Hi,
  we are working on the ADL_LRS, and we installed it on our own machine. But during our stress test we found that our platform could only handle 50 requests(write statement to platform) peer second. However we test on "https://lrs.adlnet.gov/", we found it can handle almost 250 requests(write statement to platform) peer second. We are confused about that. And we want to know why this happened and how to improve our platform  so that we can reach your level?
  In addition our machine has 4-cores, 8GB-RAM, 70GB-HDD .

We will be grateful if you can help us.^_^

**Comment by ljwolford** [comment]
Hello,
I'm not sure how you're running your LRS but I suggest using the setup we have listed [here](https://github.com/adlnet/ADL_LRS/wiki/Using-Nginx-for-Production). The only other major difference we have is we have a separate dedicated machines: one that only runs the Postgresql DB and one that runs the web server.

Hope this helps.

**Comment by HeyLynne** [comment]
Hello,
We just follow the instructions to install the ADL_LRS, but we didn't install the Nginx. Now we run Postgresql DB and web server in one machine. And we are curious about how to separate the Postgresql DB and web server in two machines. Can you give us some instructions?
We will grateful for your help~ Thanks~~

**Comment by ljwolford** [comment]
https://docs.djangoproject.com/ja/1.9/ref/settings/#host
http://www.postgresql.org/docs/9.4/static/runtime-config-connection.html
http://www.postgresql.org/docs/9.4/static/auth-pg-hba-conf.html

Those are the pages we used for our setup. You have to specify the host and port in the django settings that the postgresql server is running on. In the postgresql confs you have to specify the django host. Hope this helps.

**Comment by HeyLynne** [comment]
We did it just like you  told us.It decrease the respond time. But the requests didn't increase. But we didn't use Nginx, we are going to try to install Nginx~ Thank for your help~

**Comment by HeyLynne** [comment]
Hi,
We installed Nginx, and separated web server and postgresql. Now our machine can handle about 250 requests. Thank so much. I suggest that you could remind others to install Nginx after install ADL_LRS in the "code" part. Nginx really helps a lot.
Thanks for your help a lot~
