### ISSUE TITLE
Forward Statements

### ISSUE THREAD

**Issue by DaTebe** [adlnet/ADL_LRS#395]
Hi,

is it possible to forward all statements to an additional endpoint?
I want to log all statements in an additional Database.

Many Thanks in advance!

**Comment by ljwolford** [comment]
Hello,

Currently the only way to forward statements is directly to another client through our web hooks API. Our webhooks wiki page has in-detail instructions to set them up (https://github.com/adlnet/ADL_LRS/wiki/Webhooks). I think in your case since you want to forward all of your statements, you could just give the 'filters' value an empty bracket.

Hope this helps

**Comment by DaTebe** [comment]
Hi, Thanks for your reply. The endpoint can be anything? E.g. a node app? In my case I want to forward everything to logstash.
Do you think it is possible? 

I will try your filter approach tomorrow.

Thank you

**Comment by ljwolford** [comment]
As long as your app is constantly listening and will accept JSON data from the LRS endpoint it should be possible

**Comment by DaTebe** [comment]
I've tried the web hooks but had no success. Maybe I have an misconception on how these web hooks work.
My idea was to set a web hook for a user. And every time a user sends a request, the web hook is invoked and forwards the statement to the given endpoint.

Is this correct from the conceptual point of view?

**Comment by ljwolford** [comment]
#398 added it back in.

That's exactly how we intend the webhooks to work...you will pretty much be a guinea pig with them since we only implemented them for a few internal demos we were working on and they are not actually part of the xAPI spec. Please let me know when/if they don't work for you. Thanks

**Comment by DaTebe** [comment]
I have tested the webhook but was not able to receive something. The filters I've tried:

`[]` and `{"actor":[]}`

I set up a nodejs app which listens on `localhost/xapi` and `localhost/xapi/statements`
I checked on GET, POST and PUT.

What could I try next?

**Comment by ljwolford** [comment]
Hmm look at the celery logs to see if you see something similar to this line in them:
`"Sending statements to hook endpoint localhost/xapi"`

It logs that before it POSTs it to the endpoint, then afterwards it will log the response code from the endpoint as well:
`"Response code for sending statements to hook endpoint localhost/xapi : <code> - <content>"`

**Comment by DaTebe** [comment]
I have three log files: `celery_tasks.log`, `outworker.log` and `errworker.log`.
The first two are empty. The last contains a lot of `Task lrs.tasks.check_activity_metadata...`
I didn't found anything with "Sending..."

**Comment by DaTebe** [comment]
I played a little bit with the webhooks and filters. I also checked that USE_HOOKS is True. Also tried to delete everything and did a `fab setup_env` and `fab setup_lrs`.

Nothing seems to change.

**Comment by ljwolford** [comment]
Hmm with nothing happening or appearing in the logs it's hard to diagnose. You can put your own log statements in tasks.py by using these:

`celery_logger.info("Debug statement here")`

It will log to the celery_tasks.log file. Whenever you change the file and save it, be sure to restart the process:

`sudo restart <celerylrs or whatever you named it>`

**Comment by DaTebe** [comment]
Okay. The webhooks work!
I added a debug message and restarted celery. It seems to me, that I just needed to restart celery.

Many thanks for your help!

**Comment by ljwolford** [comment]
Awesome I'm glad it's working! You shouldn't have to restart celery every time you restart the LRS, it just depends on what's being changed. If something breaks in celery or you make a code change in any celery config or tasks files there is no auto-reload so you have to do it manually.

**Comment by DaTebe** [comment]
In my case I just shut down my computer. Restarted it and did a `./manage.py runserver`.
The webhooks didn't work. I restarted celery and it worked again. What could have changed?

**Comment by ljwolford** [comment]
Not sure....celery could have been hiccuping since you weren't getting any responses from it and just needed a reboot.

**Comment by DaTebe** [comment]
Hm, I don't know why I always have to restart celery. 
I think this issue can be closed, as forwarding works now works perfectly!
