### ISSUE TITLE
django.request: Not Found

### ISSUE THREAD

**Issue by DaTebe** [adlnet/ADL_LRS#401]
A new day, a new problem =)

I try to post statements from Moodle and use the moodle_logstore xapi plugin. 
I know, it's up to the developer to make their plugins work. But maybe you have seen this issue before?

It seems to me, that the LRS tries to use the whole URL as path:

`django.request: Not Found: /http:/localhost:8000/xapi/statements`

**Comment by ljwolford** [comment]
I have not come across the issue before. I'll leave this up for awhile in hopes someone else has.

**Comment by DaTebe** [comment]
I've installed everything on a new machine and it works without problems. Must be something strange on my machine. I think this can be closed.

Sorry for wasting your time!
