### ISSUE TITLE
See Statements from other authorities

### ISSUE THREAD

**Issue by DaTebe** [adlnet/ADL_LRS#402]
Hi,

I wonder why it is possible to see all Statements in the LRS?
I use 2 accounts. If I want to use the xAPI Statementviewer with my first account I don't want to see the statements from the second account and vice versa. 

Can I configure the LRS do behave like I want? In my use case this behavior would lead to privacy problems.

Many Thanks in advance, Daniel

**Comment by ljwolford** [comment]
It was made with the intent of being completely open and transparent so it was easier to see xapi behaviors with all of the initial tools built for it. It could be configured but off the top of my head I don't know how involved it would be. You would have to include the user's auth with the statement queries in the `retrieve_statement.py` file

**Comment by DaTebe** [comment]
I'm not the python pro. Is there something I have to do when I change the code? Do I have to rebuild something?

**Comment by ljwolford** [comment]
Nope you just have to restart the LRS (it will restart itself if you're just using the runserver command). If something is wrong it'll throw you the stack trace.

**Comment by DaTebe** [comment]
Hi,

I have set `request['auth']['statements_mine_only'] = True` in the `authorization.py`. This seems to work very well for me.

Do you think this could cause problems? As far as I can tell oAuth uses the same mechanism and does also only return it's own account statements.

**Comment by ljwolford** [comment]
That just may work. Are you setting that in the http_auth_helper function whenever the user and agent get set after it authenticates the incoming request?

**Comment by DaTebe** [comment]
I've just set the line of code (`request['auth']['statements_mine_only'] = True`) after line 183 in the `authorization.py`.
So no user can get statements of other users. In my case this is sufficient.

**Comment by ljwolford** [comment]
Yup that's exactly where. Awesome...closing now since it works.
