### ISSUE TITLE
Webhook to specific endpoint will not be saved

### ISSUE THREAD

**Issue by DaTebe** [adlnet/ADL_LRS#403]
Hello!

I've played around with your webhooks and it works very well so far. Now I have a problem with an endpoint.

I've tried to use this endpoint: `http://logstash:5001` But it will not be saved. Is there anything I must consider? (Other endpoints like `http://localhost:5001` work without problems)

EDIT (Additional Information): It seems that all endpoint without top level domain (except localhost) will not be saved. 

EDIT 2: I think django does not allow such URLs. My python is very bad, so for my usecase I will deactivate the URL validation. But maybe you can fix this? Or tell me more about why the URLs are not allowed.

**Comment by ljwolford** [comment]
Since the webhook information is being saved as a JSON blob, there shouldn't be any type of URL validation happening. If you check `/admin` on your LRS instance you should be able to see any saved webhook configs. Check to be sure it's saved there and if so then something is up with the `requests` library being used to send the request.

**Comment by DaTebe** [comment]
The URL validation is happening when saving the webhook. It's in the `forms.py` at line 35. I've overwritten the URL validation function with this code placed at line 3:

```
from django.forms import URLField as DefaultUrlField
from django.core.validators import URLValidator

class URLField(DefaultUrlField):
    myregex = '(http[s]?:\/\/(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+)'
    default_validators = [URLValidator(regex=myregex)]
```

I don't know if it's good practice in python. But for me it did work and now webhooks without toplevel domain will be saved.

**Comment by ljwolford** [comment]
Marked as bug to fix later
