### ISSUE TITLE
Web Hook: 'UUID' object has no attribute 'replace'

### ISSUE THREAD

**Issue by DaTebe** [adlnet/ADL_LRS#412]
Hi,

I wonder if someone of you ever came across this error: `AttributeError: 'UUID' object has no attribute 'replace'`

The full trace is:

```
2016-07-07 13:29:09,054 [INFO] lrs.views: 
Exception while processing: /xapi/statements
2016-07-07 13:29:09,055 [ERROR] lrs.views: 'UUID' object has no attribute 'replace'
Traceback (most recent call last):
  File "./lrs/views.py", line 205, in handle_request
    return processors[path][req_dict['method']](req_dict)
  File "./lrs/utils/req_process.py", line 131, in statements_post
    check_statement_hooks(stmt_ids) #check_statement_hooks.delay(stmt_ids)
  File "/workspace/env/lib/python2.7/site-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/workspace/env/lib/python2.7/site-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "./lrs/tasks.py", line 50, in check_statement_hooks
    stmt_ids = [uuid.UUID(st) for st in stmt_ids]
  File "/usr/local/lib/python2.7/uuid.py", line 133, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'UUID' object has no attribute 'replace'
```

I did not work at this for a week now and I did not change LRS code. Maybe you have a clue what is going on? (I send my statements with the xapi Lab)

many thanks in advance!
Daniel

**Comment by DaTebe** [comment]
Hi,

I have still no idea what is going on. I've printed the content of the `stmt_ids` variable right before the critical line 50 `stmt_ids = [uuid.UUID(st) for st in stmt_ids]`.

I have two webhooks so I get two logs:
`[u'8a57309d-19ea-4c63-81d4-d77cd66532e2']`
and
`[UUID('8a57309d-19ea-4c63-81d4-d77cd66532e2')]`

What exactly is the line 50 doing?

Many Thanks in advance
Daniel

**Comment by DaTebe** [comment]
I've changed `stmt_ids = [uuid.UUID(st) for st in stmt_ids]` to `stmt_ids2 = [uuid.UUID(st) for st in stmt_ids]` and used `stmt_ids2`.

Without the change the iteration will break if there is more then one hook. (First iteration with `UUID(st)` works. Second iteration the `UUID(st)` works on an already processed `st`)


Now that works. But I have another question that pops up:
It seems, that a web hook is not bind to an LRS user. When I'm logged in I only see my own web hooks. But when I send statements, the `check_statement_hooks` function seems to consider all available web hooks. 
Is this desired behavior?

Greetings 
Daniel

**Comment by ljwolford** [comment]
The stmt_ids line you changed should be placed outside of the `for h in hooks` loop so it only traverses those once. I can eventually get a bug fix in for it.

To answer your other question, yes, anytime statements are added to the LRS it will check all of the hooks in the system. This is intended as we were using this as a demo for our already relaxed public LRS. You can lock that down by passing the user email to the task, querying for the user, then adding that to the hook query.
