### ISSUE TITLE
Fatal error on last step (fab test_lrs)

### ISSUE THREAD

**Issue by Yuxin92** [adlnet/ADL_LRS#419]
Hi everybody,

I got everything done but met a fatal error in test step. I typed fab test_lrs, kept server running, at first test cases ran well, then lots of errors appeared (because there are too many Fails, I just paste last four of them, but all failures are similar):

FAIL: test_related_agents_filter_since (lrs.tests.test_StatementFilter.StatementFilterTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/LRS/ADL_LRS/lrs/tests/test_StatementFilter.py", line 859, in test_related_agents_filter_since
    self.assertEqual(response.status_code, 200)
AssertionError: 500 != 200

======================================================================
FAIL: test_related_agents_filter_until (lrs.tests.test_StatementFilter.StatementFilterTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/LRS/ADL_LRS/lrs/tests/test_StatementFilter.py", line 651, in test_related_agents_filter_until
    self.assertEqual(resp.status_code, 200)
AssertionError: 500 != 200

======================================================================
FAIL: test_since_filter_tz (lrs.tests.test_StatementFilter.StatementFilterTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/LRS/ADL_LRS/lrs/tests/test_StatementFilter.py", line 919, in test_since_filter_tz
    self.assertEqual(resp.status_code, 204)
AssertionError: 500 != 204

======================================================================
FAIL: test_verb_filter (lrs.tests.test_StatementFilter.StatementFilterTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/LRS/ADL_LRS/lrs/tests/test_StatementFilter.py", line 999, in test_verb_filter
    self.assertEqual(resp.status_code, 200)
AssertionError: 500 != 200

----------------------------------------------------------------------
Ran 370 tests in 424.633s

FAILED (failures=142, errors=44)
Destroying test database for alias 'default'...

Fatal error: local() encountered an error (return code 1) while executing './manage.py test lrs.tests'

Aborting.

Why did this happen? How can I fix it? I saw one of similar issues in here, but I kept my server running, so that issue doesn't help...

thanks in advance,
Yuxin

**Comment by ljwolford** [comment]
It seems like something isn't setup correctly. If you look in the `logs` directory for `lrs.log` it will show you the stack traces for the errors for a better description on what's going wrong.

**Comment by ljwolford** [comment]
close due to inactivity
