### ISSUE TITLE
LRS will not allow an contextActivities to be empty

### ISSUE THREAD

**Issue by kgrandis** [adlnet/ADL_LRS#423]
My reading of the xAPI spec says the contextActivities keys MUST be of a certain type, but I don't see where it MUST contain a key to begin with. It seems like you should be able to pass in an empty contextActivities. Could be mistaken here, but thought I would pass along in case.

where contextActivities = {}

`2016-09-08 23:34:05,682 [ERROR] lrs.views: contextActivities must contain at least one key/value pair
Traceback (most recent call last):
  File "./lrs/views.py", line 213, in handle_request
    req_dict = validators[path][r_dict['method']](r_dict)
  File "./lrs/utils/authorization.py", line 36, in inner
    return func(request, *args, **kwargs)
  File "./lrs/utils/req_validate.py", line 89, in statements_post
    raise BadRequest(e.message)
BadRequest: contextActivities must contain at least one key/value pair
`

**Comment by ljwolford** [comment]
I think it was implied in the old 1.0.2 spec that properties should not be empty. It was explicitly stated in the newer 1.0.3 spec:

https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI-Data.md#dataconstraints


Thanks for the heads up!

**Comment by kgrandis** [comment]
perfect. thanks for the spec reference.
