### ISSUE TITLE
State Error 404

### ISSUE THREAD

**Issue by kelvinsleonardo** [adlnet/ADL_LRS#425]
Hi, 
I am using the moddle's Tincan plugin "https://moodle.org/plugins/mod_tincanlaunch" however after send a state there'a an 404 error according to image below

Log Server LRS
![selecao_048](https://cloud.githubusercontent.com/assets/7854286/18647001/6a3cb508-7e8a-11e6-8c47-d8c2453275af.png)

Message Error plugin Tincan
![selecao_050](https://cloud.githubusercontent.com/assets/7854286/18647096/d1db9f26-7e8a-11e6-9790-8e1be0a29399.png)

**Comment by ljwolford** [comment]
Hello,

I don't have any experience with this plugin but it looks like your LRS endpoint is being duplicated somewhere while making the request. I would check your settings to make sure you're only appending the relative path for the state resource to the endpoint.

**Comment by kelvinsleonardo** [comment]
Configuration plugin tincan moodle
![print](https://cloud.githubusercontent.com/assets/7854286/18673076/c8853662-7f20-11e6-95af-f077dd056b2e.png)

**Comment by ljwolford** [comment]
It would seem everything looks correct there. Not sure why the endpoint is being duplicated

**Comment by kelvinsleonardo** [comment]
I tried to install in localhost, but is returning the same message error.

**Comment by ljwolford** [comment]
Can you try replicating the request using a different tool? Obviously not keeping the endpoint in the path either.  Somehow the routing is passing the endpoint in your path.

**Comment by kelvinsleonardo** [comment]
I had tried, and it worked normally. The plugin tincan in the moodle sends the same request.
![captura_de_tela](https://cloud.githubusercontent.com/assets/7854286/18724838/3c30c72c-8014-11e6-8102-9d466379bbe4.png)

**Comment by ljwolford** [comment]
Something might be wrong then with your web server and how it is forwarding requests to your LRS. I see that state has also been sent successfully, and retrieved successfully with the public ADL LRS.

**Comment by kelvinsleonardo** [comment]
Yes. I used this guide of installation https://github.com/adlnet/ADL_LRS :/

**Comment by ljwolford** [comment]
I think it is something different, outside of the LRS that is wrong since the public LRS has the same setup. The LRS is simply receiving the bad URL.

**Comment by kelvinsleonardo** [comment]
I tested with public LRS and is working https://lrs.adlnet.gov/

**Comment by ljwolford** [comment]
Good...the public LRS uses the same setup/install. What are you using to host your LRS?

**Comment by kelvinsleonardo** [comment]
A server Debian GNU/Linux 8.

**Comment by ljwolford** [comment]
closed due to inactivity

**Comment by bvukas** [comment]
I am having the same issue with https://moodle.org/plugins/logstore_xapi, even though ADL_LRS works correctly from Postman. 

Could it be the same issues like this one https://github.com/Brightcookie/lxHive/issues/91

![image](https://cloud.githubusercontent.com/assets/2697464/24496678/2bf910a2-1539-11e7-81ef-df87c1ea7e91.png)

**Comment by ljwolford** [comment]
Yes, it appears your full URL is being appended to the path. So instead of POSTing to:

`http://192.168.33.10:8000/xAPI/statements`, it is trying to POST to

`http://192.168.33.10:8000/http://192.168.33.10:8000/xAPI/statements`
