### ISSUE TITLE
String incides must be integers, not str

### ISSUE THREAD

**Issue by DustinDobernig** [adlnet/ADL_LRS#430]
Using the xapi-jqm course demo to test my ADL_LRS installation. I am receiving an error of "String incides must be integers, not str" error. Not sure why as the request payload being sent is valid json. Any help? Here is the traceback:

2016-10-07 10:37:30,781 [INFO] lrs.views: 
Exception while processing: /lrs/xapi/statements
2016-10-07 10:37:30,782 [ERROR] lrs.views: string indices must be integers, not str
Traceback (most recent call last):
  File "/opt/bitnami/apps/django/django_projects/lrs/src/lrs/views.py", line 214, in handle_request
    req_dict = validators[path][r_dict['method']](r_dict)
  File "/opt/bitnami/apps/django/django_projects/lrs/src/lrs/utils/authorization.py", line 35, in inner
    return func(request, _args, *_kwargs)
  File "/opt/bitnami/apps/django/django_projects/lrs/src/lrs/utils/req_validate.py", line 100, in statements_post
    'payload_sha2s', None), req_dict['headers']['CONTENT_TYPE'])
  File "/opt/bitnami/apps/django/django_projects/lrs/src/lrs/utils/req_validate.py", line 63, in validate_body
    stmt, auth, payload_sha2s, content_type) for stmt in body]
  File "/opt/bitnami/apps/django/django_projects/lrs/src/lrs/utils/req_validate.py", line 73, in server_validate_statement
    if stmt['verb']['id'] == 'http://adlnet.gov/expapi/verbs/voided':
TypeError: string indices must be integers, not str
2016-10-07 10:37:32,718 [INFO] lrs.views: 
Exception while processing: /lrs/xapi/statements
2016-10-07 10:37:32,747 [ERROR] lrs.views: string indices must be integers, not str
Traceback (most recent call last):
  File "/opt/bitnami/apps/django/django_projects/lrs/src/lrs/views.py", line 214, in handle_request
    req_dict = validators[path][r_dict['method']](r_dict)
  File "/opt/bitnami/apps/django/django_projects/lrs/src/lrs/utils/authorization.py", line 35, in inner
    return func(request, _args, *_kwargs)
  File "/opt/bitnami/apps/django/django_projects/lrs/src/lrs/utils/req_validate.py", line 100, in statements_post
    'payload_sha2s', None), req_dict['headers']['CONTENT_TYPE'])
  File "/opt/bitnami/apps/django/django_projects/lrs/src/lrs/utils/req_validate.py", line 63, in validate_body
    stmt, auth, payload_sha2s, content_type) for stmt in body]
  File "/opt/bitnami/apps/django/django_projects/lrs/src/lrs/utils/req_validate.py", line 73, in server_validate_statement
    if stmt['verb']['id'] == 'http://adlnet.gov/expapi/verbs/voided':
TypeError: string indices must be integers, not str

**Comment by ljwolford** [comment]
Hmm that is interesting.  Are you able to consistently reproduce it? And if so, can you share the steps you are taking to produce it? Thanks

**Comment by DustinDobernig** [comment]
When I did a "print stmt" I can see that It prints each individual character of the body variable.  Does the entire JSON body need to be wrapped in an array?  

[Tue Oct 11 09:40:12.506905 2016] [:error] [pid 33030] c
[Tue Oct 11 09:40:12.506972 2016] [:error] [pid 33030] o
[Tue Oct 11 09:40:12.507039 2016] [:error] [pid 33030] u
[Tue Oct 11 09:40:12.507106 2016] [:error] [pid 33030] r
[Tue Oct 11 09:40:12.507173 2016] [:error] [pid 33030] s
[Tue Oct 11 09:40:12.507240 2016] [:error] [pid 33030] e
[Tue Oct 11 09:40:12.507308 2016] [:error] [pid 33030] /
[Tue Oct 11 09:40:12.507375 2016] [:error] [pid 33030] "
[Tue Oct 11 09:40:12.507442 2016] [:error] [pid 33030] ,
[Tue Oct 11 09:40:12.507509 2016] [:error] [pid 33030] "
[Tue Oct 11 09:40:12.507575 2016] [:error] [pid 33030] d
[Tue Oct 11 09:40:12.507642 2016] [:error] [pid 33030] e
[Tue Oct 11 09:40:12.507762 2016] [:error] [pid 33030] f
[Tue Oct 11 09:40:12.507832 2016] [:error] [pid 33030] i
[Tue Oct 11 09:40:12.507900 2016] [:error] [pid 33030] n
[Tue Oct 11 09:40:12.507967 2016] [:error] [pid 33030] i
[Tue Oct 11 09:40:12.508034 2016] [:error] [pid 33030] t
[Tue Oct 11 09:40:12.508101 2016] [:error] [pid 33030] i
[Tue Oct 11 09:40:12.508169 2016] [:error] [pid 33030] o
[Tue Oct 11 09:40:12.508236 2016] [:error] [pid 33030] n
[Tue Oct 11 09:40:12.508303 2016] [:error] [pid 33030] "
[Tue Oct 11 09:40:12.508370 2016] [:error] [pid 33030] :
[Tue Oct 11 09:40:12.508437 2016] [:error] [pid 33030] {
[Tue Oct 11 09:40:12.508504 2016] [:error] [pid 33030] "
[Tue Oct 11 09:40:12.508571 2016] [:error] [pid 33030] n
[Tue Oct 11 09:40:12.508638 2016] [:error] [pid 33030] a
[Tue Oct 11 09:40:12.508706 2016] [:error] [pid 33030] m
[Tue Oct 11 09:40:12.508773 2016] [:error] [pid 33030] e
[Tue Oct 11 09:40:12.508840 2016] [:error] [pid 33030] "
[Tue Oct 11 09:40:12.508906 2016] [:error] [pid 33030] :
[Tue Oct 11 09:40:12.508973 2016] [:error] [pid 33030] {
[Tue Oct 11 09:40:12.509041 2016] [:error] [pid 33030] "

**Comment by ljwolford** [comment]
It should be an array of dictionaries at this point, not a string in an array...can you share what you did exactly with the course demo to see if i can reproduce it?

Thanks

**Comment by DustinDobernig** [comment]
I didn't make changes to the course whatsoever. It is simply the Demo course from https://github.com/adlnet/xapi-jqm. And I pointed to the endpoint of newest adl-lrs github version installation. When I print out "body" from the validate_body function this is what it returns: 

{"actor":{"mbox":"mailto:test@gmail.com","name":"test"},"verb":{"id":"http://example.com/xapi/verbs/read","display":{"en-US":"read"}},"context":{"contextActivities":{"parent":[{"id":"http://mywebsite/course/","definition":{"name":{"en-US":"How to Make French Toast xapi-jqm Course Demo"},"description":{"en-US":"A sample HTML5 mobile app with xAPI tracking that teaches you how to make french toast."}},"objectType":"Activity"},{"id":"http://mywebsite/course/toc","definition":{"name":{"en-US":"How to Make French Toast xapi-jqm Course Demo: toc"}},"objectType":"Activity"}]}},"object":{"id":"http://mywebsite/course/toc/list","objectType":"Activity","definition":{"name":{"en-US":"How to Make French Toast xapi-jqm Course Demo: toc, page: list"}}},"id":"7812bb09-f8c3-452a-96e1-f494ebfeb38a"}

Is this the expected output?

**Comment by ljwolford** [comment]
The body has been transformed by this point so that all statements have been validated and transformed from a JSON string to dictionary. All of the statements are then placed in an array.  The whole body printed from the validate_body function should be an array...in this case an array containing a single statement that is of type dict. Have you gotten this error while running against the public LRS? (https://lrs.adlnet.gov/xapi/)

**Comment by DustinDobernig** [comment]
I do not received the error when I change the endpoint to (https://lrs.adlnet.gov/xapi/) as the endpoint. Let me clarify that I have NOT setup adl-lrs on my server using fab and virtualenv. Celery and supervisor however were setup according to your guide and function as expected I believe. This installation was done on a Bitnami Django stack because the other app I have built will work along side this LRS but installed all libraries off requirements.txt. Is it possible that I'm missing something and apache is not configured correctly or a library isnt functioning? I'm failing to see where its malfunctioning because the course works and writes the agents in the database but then fails at that point in the traceback.

**Comment by ljwolford** [comment]
I would think if a library isn't functioning it would have failed earlier in the stack...did you run the associated tests with it to see if all of those pass? I'm surprised it got to this point without breaking earlier.

**Comment by DustinDobernig** [comment]
```
Ran 370 tests in 230.894s
OK

```
Everything passed ok.  When I ran the tests and printed the body of that function it returned in this format:
``
[{u'verb': {u'id': u'http://example.com/verbs/missed', u'display': {u'en-US': u'missed'}}, u'actor': {u'mbox': u'mailto:s@s.com', u'objectType': u'Agent'}, u'object': {u'mbox': u'mailto:john@john.com', u'name': u'john', u'objectType': u'Agent'}, 'id': u'3acc397c-9151-11e6-a600-000d3a608129'}]
``

When I print it out when the course makes a post it return this format:

``{"actor":{"mbox":"mailto:test@gmail.com","name":"test"},"verb":{"id":"http://example.com/xapi/verbs/read","display":{"en-US":"read"}},"context":{"contextActivities":{"parent":[{"id":"http://mywebsite/course/","definition":{"name":{"en-US":"How to Make French Toast xapi-jqm Course Demo"},"description":{"en-US":"A sample HTML5 mobile app with xAPI tracking that teaches you how to make french toast."}},"objectType":"Activity"},{"id":"http://mywebsite/course/toc","definition":{"name":{"en-US":"How to Make French Toast xapi-jqm Course Demo: toc"}},"objectType":"Activity"}]}},"object":{"id":"http://mywebsite/course/toc/list","objectType":"Activity","definition":{"name":{"en-US":"How to Make French Toast xapi-jqm Course Demo: toc, page: list"}}},"id":"7812bb09-f8c3-452a-96e1-f494ebfeb38a"}
``
 I dont know why its not including the brackets and why its not returning as unicode strings. Any insight?

**Comment by ljwolford** [comment]
Yeah i'm not sure why it's not placing those statements in a list. I hooked up the course to my local lrs and was able to print out:

`[{u'id': u'7cb21ef8-683e-4309-aa66-a64337ed916c', u'verb': {u'id': u'http://example.com/xapi/verbs/read', u'display': {u'en-US': u'read'}}, u'context': {u'contextActivities': {u'parent': [{u'definition': {u'name': {u'en-US': u'How to Make French Toast xapi-jqm Course Demo'}, u'description': {u'en-US': u'A sample HTML5 mobile app with xAPI tracking that teaches you how to make french toast.'}}, u'id': u'http://adlnet.gov/xapi/samples/xapi-jqm/course/', u'objectType': u'Activity'}, {u'definition': {u'name': {u'en-US': u'How to Make French Toast xapi-jqm Course Demo: toc'}}, u'id': u'http://adlnet.gov/xapi/samples/xapi-jqm/course/toc', u'objectType': u'Activity'}]}}, u'actor': {u'mbox': u'mailto:test@test.com', u'name': u'test', 'objectType': 'Agent'}, u'object': {u'definition': {u'name': {u'en-US': u'How to Make French Toast xapi-jqm Course Demo: toc, page: list'}}, u'id': u'http://adlnet.gov/xapi/samples/xapi-jqm/course/toc/list', u'objectType': u'Activity'}}]`

If you look in the statements_post and statements_put functions, you can see it's putting the body into an list so everything in validate_body should be as well.

**Comment by ljwolford** [comment]
closed due to inactivity
