### ISSUE TITLE
python-devlibxml2-dev

### ISSUE THREAD

**Issue by bob-ludvigsen** [adlnet/ADL_LRS#448]
Hi
I´m trying to install the dependencies on a Ubuntu 16, I get the error below. is that lib renamed or remowed?

root@lrs:/# apt-get install git fabric python-setuptools python-dev\libxml2-dev libxslt1-dev gcc
Reading package lists... Done
Building dependency tree
Reading state information... Done

E: Unable to locate package python-devlibxml2-dev

**Comment by ljwolford** [comment]
Hi,
It looks like it's a copy/paste error. Those are two different packages, `python-dev` and `libxml2-dev`. That should work if you try it.

Thanks.

**Comment by ljwolford** [comment]
closed due to inactivity
