### ISSUE TITLE
Unable to use the ADL_LRS API from an example_script based on TinCanPython

### ISSUE THREAD

**Issue by gtoffoli** [adlnet/ADL_LRS#456]
Last month (13 January) I installed your reference implementation on an Ubuntu 14 server.
I met no problems in doing the installation and was able to access the LRS from its web interface.

Then I tried to access the LRS through its API, from a Python shell, using the TinCanPython library and the code of the example_script I found in the same site.
And I was puzzled by inconsistent results.

After constructing the RemoteLRS, Agent, Verb, Activity, Context and Statement objects, when excuting the save_statement method of the RemoteLRS I got a response with a 500 status.
But, by accessing the LRS from its web interface (the Django application), I saw that the statement had been correctly recorded!
I was also able to retrieve the statement, by executing the subsequent code of the example_script and putting as argument the literal id that I took from the web user interface, in place of the content id I should have got from the response to the save_statement method.

The test above induced me to think that there was some bug in the TinCanPython library or in the example_script. I also created an issue at TinCanPython.

But, a few days later, using exactly the same script, I've repeated the test using an "Explore plan" on Vax LRS. And I was able to both save the statement on the remote LRS and to retrieve it.

What do you suggest to do? Thanks in advance.

**Comment by ljwolford** [comment]
Look at your lrs or celery logs to see if they display the 500 error for you. If the statement was saved to the system fine, I'm going to guess something on the celery end isn't working correctly and crashed. All those processes do is check the activity id and try to retrieve any metadata from it, so while the statement saved, it could just be returning that 500 error.

**Comment by gtoffoli** [comment]
Thank you! The lrs log confirms that there was a socket error at the AMQP level.
