### ISSUE TITLE
Support proxy https (Ex: Amazon ALB)

### ISSUE THREAD

**Issue by sanglt** [adlnet/ADL_LRS#475]
Correct detect https for Amazon ALB proxy.

I setup ALB with only https protocol. And the dockerimage of adl-lrs. The request.is_secure always return false with my setup, and its made the base url show incorrect url.

After use this setting, the page is working correct

Fixed in #474

**Comment by vbhayden** [comment]
There isn't an officially supported Docker image for the ADL LRS as far as I know, and the closest one I can find is (this 3rd party image /dirichlet/lrs)[https://hub.docker.com/r/dirichlet/lrs/].  

The recommended production configuration for the ADL LRS does use a proxy with SSL enabled (nginx) and those steps are outlined in the [uWSGI / nginx wiki](https://github.com/adlnet/ADL_LRS/wiki/Using-uWSGI-with-Nginx).  

We don't really have the bandwidth to support 3rd-party modifications or images of the ADL LRS, but I do have a set of simplified installation instructions that might get you (or whoever's reading this after the 9 months in isolation) a functional example with SSL: [https://github.com/vbhayden/adl-lrs-installer](https://github.com/vbhayden/adl-lrs-installer).

Closing this unless there are other people having proxy issues.
