### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by Moh1267** [adlnet/ADL_LRS#476]
Hi,
I am wondering whether possible to use this LRS on Windows. If yes, how can install it ?
Thank you in advance.

**Comment by vbhayden** [comment]
It's possible and I have it running on my windows 8.1 machine, but did not document the steps.  There are some changes that need to be made in the Fabfile.py and postgres iirc, but yes it's possible.

**Comment by Moh1267** [comment]
Thank you vbhayden for your answer,
Could you tell please  me which change are you did? 
Thank you in advance.

**Comment by vbhayden** [comment]
Added a pull request with updated instructions.  There's a branch for it called "windows-instructions" or something -- let me know if those are helpful to you.

**Comment by Moh1267** [comment]
Thank you very much vbhayden. 
I am going to install it in my machine and I will tell you whether it works

**Comment by vbhayden** [comment]
Marking this as closed due to inactivity, but I've created a branch on this repo with a windows-tailored installation ReadMe.
