### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by richtera** [adlnet/ADL_LRS#481]
I can login and go through the site but I cannot get reset_password to work. It just hangs and the uwsgi handler crashes. Trying to run it locally doesn't show any POST hits to the server but the browser has a pending request which then times out. I followed the instructions but haven't recently user django so there might be something slightly off. I tested the SMTP setting separately to make sure it's not that.
Unfortunately none of the logs show an actual error :-(

**Comment by vbhayden** [comment]
Hm, do you know if the actual ADL LRS at https://lrs.adlnet.gov has sent you emails ?
