### ISSUE TITLE
Migration plan for python3 due to Python2 EOL already being passed

### ISSUE THREAD

**Issue by fullofentropy** [adlnet/ADL_LRS#495]
Python2 reached its end of life in Jan 2020.  Is there any plan to migrate this out of python 2 and into python 3 from a security perspective?

**Comment by vbhayden** [comment]
@fullofentropy morning!

Somehow never saw this, but yep we've been tracking this for awhile.  

I went in over the weekend and did the migration to Python 3, including updated dependencies and a new deployment setup using Docker.  That will be added as a PR on here today once I reorganize the folder structure a bit.

**Comment by bRRRITSCOLD** [comment]
@vbhayden Any chance the PR was completed?

**Comment by vbhayden** [comment]
Branch was pushed yesterday at https://github.com/adlnet/ADL_LRS/tree/python3

We'll tag the current version as the last viable Python 2 release and then hopefully get this one moved over before Friday.  Team is updating documentation and the Docker instructions atm.

**Comment by vbhayden** [comment]
Forgot to close this out, Python 3 is currently live on our preview server and will be updated to live along with the xAPI 2.0 patch in the next few weeks.

Thanks for the reminder all!
